name: Run e2e Playwright tests
on:
  pull_request:
  workflow_dispatch:

# if this branch is pushed back to back, cancel the older branch's workflow
concurrency:
  group:  ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  DATABASE_URL: 'file:./dev.db'
  PORT: 3001
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  KAFKAJS_NO_PARTITIONER_WARNING: 1 # less kafka noise

jobs:
  e2e-test-pw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Cache Playwright Browser
        uses: actions/cache@v4
        with:
          paht: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            playwright-${{ runner.os }}
        
      - name: Install dependencies
        run: yarn ci 

      - name: Install Playwright Chromium Only
        run: yarn playwright install chromium

      # Start Kafka before running the tests
      # Locally if no Kafka, the kafka version of the e2e test just doesn't run

      - name: Start Kafka
        continue-on-error: true # if we hit the docker pull limit, no kafka
        run: docker compose -f ./src/events/kafka-cluster.yml up -d --no-recreate

      - name: Run Playwright Tests
        run: yarn pw:run

      # Stop Kafka after tests are completed
      - name: Stop Kafka
        continue-on-error: true
        if: always()
        run: docker compose -f ./src/events/kafka-cluster.yml down

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3
